sdkversion: 5.0.0
name: databaseApp
version: '1.0'
vendor: rhomobile
build: debug
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator8.1
  provisionprofile: ''
  codesignidentity: iPhone Developer
  entitlements: ''
  BundleIdentifier: com.rhomobile.databaseapp
  BundleURLScheme: databaseapp
  production:
    ipa_itunesartwork_image: ./production/iTunesArtwork.png
wp8:
  productid: 77221f40-cbb1-0132-39c1-00000b5a4ce5
android:
  manifest_template: AndroidManifest.erb
  version: 2.3.3
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E
wm: ''
extensions:
- rhoconnect-client
app_type: rhoelements
capabilities: []
